### ISSUE TITLE
Launchy.open with Pathname

### ISSUE THREAD

**Issue by dmke** [copiousfreetime/launchy#101]
Hi there!

I have noticed that using a [Pathname](http://ruby-doc.org/stdlib/libdoc/pathname/rdoc/index.html) instance as parameter for `open` will raise an error:

```
~$ irb -rlaunchy -rpathname
?> [RUBY_VERSION, Launchy::VERSION]
=> ["2.2.3", "2.4.3"]
?> Launchy.open Pathname.new(__dir__)
Launchy::Error: Failure in opening uri #<Pathname:.> with options {}: Can't convert Pathname into String.
from /home/dm/.rbenv/versions/ruby-2.1/gemsets/test/gems/launchy-2.4.3/lib/launchy.rb:34:in `rescue in open`
```

In most of my projects I'm using Pathname objects instead of plain strings (think of PDF generation in Rails apps), and for debugging and testing purposes I often use Launchy to open these files. The current behaviour forces me to use `Launchy.open pdf.path.to_s` (instead of just `pdf.path`).

I wonder if I could/should provide a patch for [`Launchy.string_to_uri`](https://github.com/copiousfreetime/launchy/blob/aed917f/lib/launchy.rb#L51), or if this is an issue I should discuss in the [addressable](https://github.com/sporkmonger/addressable) repository (cp. [`Addressable::URI.parse`](https://github.com/sporkmonger/addressable/blob/6105d13/lib/addressable/uri.rb#L99)).

What is your opinion?

**Comment by copiousfreetime** [comment]
I think  patch to `Launchy.string_to_uri` is absolutely a good way to go. It may be as simple as a `s.to_s` :smile:
