### ISSUE TITLE
About letter opener  :- Launchy Error

### ISSUE THREAD

**Issue by rk-panchal** [copiousfreetime/launchy#104]
I use letter opener for mail status and it working fine in development mode but when i deployed my app on heroku  it's working not fine and Produce following error

 Launchy::CommandNotFoundError (Unable to find a browser command. If this is unexpected, Please rerun with environment variable LAUNCHY_DEBUG=true or the '-d' commandline option

If any one face same problem and have solution for it ,Please share.
 Thanks in Advance.

**Comment by alicemomo** [comment]
Hi there,
I'm having the exact same problem. How did you solve this ?
Thanks !

**Comment by copiousfreetime** [comment]
Hi @rk-panchal, Launchy attempts to find an installed browser locally on the machine that it is running on. If you are using launchy in a remote machine/heroku/vps scenario it will attempt to launch a web browser process on that remote machine.

For Letter Opener in particular, this is addressed in its README: https://github.com/ryanb/letter_opener#remote-alternatives
