### ISSUE TITLE
The error requested that I leave a bug report here

### ISSUE THREAD

**Issue by bailey86** [copiousfreetime/launchy#106]
kbailey@holley:~/projects/learningsouq/php-getting-started$ heroku open
Opening immense-falls-5478... failed
 !    Heroku client internal error.
 !    Search for help at: https://help.heroku.com
 !    Or report a bug at: https://github.com/heroku/heroku/issues/new

    Error:       Unable to find a browser command. If this is unexpected, Please rerun with environment variable LAUNCHY_DEBUG=true or the '-d' commandline option and file a bug at https://github.com/copiousfreetime/launchy/issues/new (Launchy::CommandNotFoundError)
    Command:     heroku open
    Version:     heroku-toolbelt/3.42.22 (x86_64-linux-gnu) ruby/2.1.5
    Error ID:    e676384abf5d4caaa44d6cbdca2cb03d

    More information in /home/kbailey/.heroku/error.log

kbailey@holley:~/projects/learningsouq/php-getting-started$ 

LOG OUTPUT:

kbailey@holley:~/projects/learningsouq/php-getting-started$ cat /home/kbailey/.heroku/error.log
2015/12/03 13:15:45 running heroku-cli/4.27.7-135a760 (amd64-linux) go1.5.1 from /home/kbailey/.heroku/heroku-cli
2015/12/03 13:15:45 heroku-cli: Adding dependencies...
2015/12/03 13:16:15  done
2015/12/03 13:16:15 heroku-cli: Installing core plugins...
2015/12/03 13:16:49  done
2015/12/03 13:16:49 running heroku-cli/4.27.7-135a760 (amd64-linux) go1.5.1 from /home/kbailey/.heroku/heroku-cli
2015/12/03 13:16:49 running heroku-cli/4.27.7-135a760 (amd64-linux) go1.5.1 from /home/kbailey/.heroku/heroku-cli
2015/12/03 13:16:49 Email: 
2015/12/03 13:39:00 running heroku-cli/4.27.7-135a760 (amd64-linux) go1.5.1 from /home/kbailey/.heroku/heroku-cli
2015/12/03 13:42:45 running heroku-cli/4.27.7-135a760 (amd64-linux) go1.5.1 from /home/kbailey/.heroku/heroku-cli
2015/12/03 13:42:58 running heroku-cli/4.27.7-135a760 (amd64-linux) go1.5.1 from /home/kbailey/.heroku/heroku-cli
Heroku client internal error.
Unable to find a browser command. If this is unexpected, Please rerun with environment variable LAUNCHY_DEBUG=true or the '-d' commandline option and file a bug at https://github.com/copiousfreetime/launchy/issues/new
/usr/local/heroku/vendor/gems/launchy-2.4.3/lib/launchy/applications/browser.rb:63:in `browser_cmdline'
/usr/local/heroku/vendor/gems/launchy-2.4.3/lib/launchy/applications/browser.rb:67:in `cmd_and_args'
/usr/local/heroku/vendor/gems/launchy-2.4.3/lib/launchy/applications/browser.rb:78:in `open'
/usr/local/heroku/vendor/gems/launchy-2.4.3/lib/launchy.rb:29:in `open'
/usr/local/heroku/lib/heroku/helpers.rb:366:in `block in launchy'
/usr/local/heroku/lib/heroku/helpers.rb:257:in `action'
/usr/local/heroku/lib/heroku/helpers.rb:364:in `launchy'
/usr/local/heroku/lib/heroku/command/apps.rb:233:in `open'
/usr/local/heroku/lib/heroku/command.rb:212:in `run'
/usr/local/heroku/lib/heroku/cli.rb:30:in `start'
/usr/bin/heroku:25:in `<main>'
2015/12/03 13:45:11 running heroku-cli/4.27.7-135a760 (amd64-linux) go1.5.1 from /home/kbailey/.heroku/heroku-cli
Heroku client internal error.
Unable to find a browser command. If this is unexpected, Please rerun with environment variable LAUNCHY_DEBUG=true or the '-d' commandline option and file a bug at https://github.com/copiousfreetime/launchy/issues/new
/usr/local/heroku/vendor/gems/launchy-2.4.3/lib/launchy/applications/browser.rb:63:in `browser_cmdline'
/usr/local/heroku/vendor/gems/launchy-2.4.3/lib/launchy/applications/browser.rb:67:in `cmd_and_args'
/usr/local/heroku/vendor/gems/launchy-2.4.3/lib/launchy/applications/browser.rb:78:in `open'
/usr/local/heroku/vendor/gems/launchy-2.4.3/lib/launchy.rb:29:in `open'
/usr/local/heroku/lib/heroku/helpers.rb:366:in `block in launchy'
/usr/local/heroku/lib/heroku/helpers.rb:257:in `action'
/usr/local/heroku/lib/heroku/helpers.rb:364:in `launchy'
/usr/local/heroku/lib/heroku/command/apps.rb:233:in `open'
/usr/local/heroku/lib/heroku/command.rb:212:in `run'
/usr/local/heroku/lib/heroku/cli.rb:30:in `start'
/usr/bin/heroku:25:in `<main>'
kbailey@holley:~/projects/learningsouq/php-getting-started$ kbailey@holley:~/projects/learningsouq/php-getting-started$ cat /home/kbailey/.heroku/error.log
2015/12/03 13:15:45 running heroku-cli/4.27.7-135a760 (amd64-linux) go1.5.1 from /home/kbailey/.heroku/heroku-cli
2015/12/03 13:15:45 heroku-cli: Adding dependencies...
2015/12/03 13:16:15  done
2015/12/03 13:16:15 heroku-cli: Installing core plugins...
2015/12/03 13:16:49  done
2015/12/03 13:16:49 running heroku-cli/4.27.7-135a760 (amd64-linux) go1.5.1 from /home/kbailey/.heroku/heroku-cli
2015/12/03 13:16:49 running heroku-cli/4.27.7-135a760 (amd64-linux) go1.5.1 from /home/kbailey/.heroku/heroku-cli
2015/12/03 13:16:49 Email: 
2015/12/03 13:39:00 running heroku-cli/4.27.7-135a760 (amd64-linux) go1.5.1 from /home/kbailey/.heroku/heroku-cli
2015/12/03 13:42:45 running heroku-cli/4.27.7-135a760 (amd64-linux) go1.5.1 from /home/kbailey/.heroku/heroku-cli
2015/12/03 13:42:58 running heroku-cli/4.27.7-135a760 (amd64-linux) go1.5.1 from /home/kbailey/.heroku/heroku-cli
Heroku client internal error.
Unable to find a browser command. If this is unexpected, Please rerun with environment variable LAUNCHY_DEBUG=true or the '-d' commandline option and file a bug at https://github.com/copiousfreetime/launchy/issues/new
/usr/local/heroku/vendor/gems/launchy-2.4.3/lib/launchy/applications/browser.rb:63:in `browser_cmdline'
/usr/local/heroku/vendor/gems/launchy-2.4.3/lib/launchy/applications/browser.rb:67:in `cmd_and_args'
/usr/local/heroku/vendor/gems/launchy-2.4.3/lib/launchy/applications/browser.rb:78:in `open'
/usr/local/heroku/vendor/gems/launchy-2.4.3/lib/launchy.rb:29:in `open'
/usr/local/heroku/lib/heroku/helpers.rb:366:in `block in launchy'
/usr/local/heroku/lib/heroku/helpers.rb:257:in `action'
/usr/local/heroku/lib/heroku/helpers.rb:364:in `launchy'
/usr/local/heroku/lib/heroku/command/apps.rb:233:in `open'
/usr/local/heroku/lib/heroku/command.rb:212:in `run'
/usr/local/heroku/lib/heroku/cli.rb:30:in `start'
/usr/bin/heroku:25:in `<main>'
2015/12/03 13:45:11 running heroku-cli/4.27.7-135a760 (amd64-linux) go1.5.1 from /home/kbailey/.heroku/heroku-cli
Heroku client internal error.
Unable to find a browser command. If this is unexpected, Please rerun with environment variable LAUNCHY_DEBUG=true or the '-d' commandline option and file a bug at https://github.com/copiousfreetime/launchy/issues/new
/usr/local/heroku/vendor/gems/launchy-2.4.3/lib/launchy/applications/browser.rb:63:in `browser_cmdline'
/usr/local/heroku/vendor/gems/launchy-2.4.3/lib/launchy/applications/browser.rb:67:in `cmd_and_args'
/usr/local/heroku/vendor/gems/launchy-2.4.3/lib/launchy/applications/browser.rb:78:in `open'
/usr/local/heroku/vendor/gems/launchy-2.4.3/lib/launchy.rb:29:in `open'
/usr/local/heroku/lib/heroku/helpers.rb:366:in `block in launchy'
/usr/local/heroku/lib/heroku/helpers.rb:257:in `action'
/usr/local/heroku/lib/heroku/helpers.rb:364:in `launchy'
/usr/local/heroku/lib/heroku/command/apps.rb:233:in `open'
/usr/local/heroku/lib/heroku/command.rb:212:in `run'
/usr/local/heroku/lib/heroku/cli.rb:30:in `start'
/usr/bin/heroku:25:in `<main>'
kbailey@holley:~/projects/learningsouq/php-getting-started$

**Comment by copiousfreetime** [comment]
@bailey86 Can you please rerun that with the environment variable `LAUNCHY_DEBUG=true` set?

**Comment by copiousfreetime** [comment]
Closing since I have had no feedback.
