### ISSUE TITLE
disable messaging?

### ISSUE THREAD

**Issue by mockdeep** [copiousfreetime/launchy#109]
I'm writing a tool that opens multiple browser tabs, but one annoying aspect of it is that it outputs every time a new tab is opened:

```
Created new window in existing browser session.
Created new window in existing browser session.
Created new window in existing browser session.
Created new window in existing browser session.
Created new window in existing browser session.
Created new window in existing browser session.
```

Is there a way to disable this messaging?

**Comment by copiousfreetime** [comment]
@mockdeep That message is not coming from launchy, that is coming from your browser or somehwere. I have code in place that captures all the output from the spawned processes so I'm not exactly sure what is causing that output. What browser and OS are you on i'll see if there is anything that can be done. Are you using Vagrant? 

Take a look at a previous issue on this and see if anything there helps. Personally I'm unable to duplicate this, so any assistance you can provide would be most welcome.

https://github.com/copiousfreetime/launchy/issues/51#issuecomment-177308911

**Comment by mockdeep** [comment]
@copiousfreetime I'm running Chrome on Linux Mint, no VM. I see the same message when I run `xdg-open https://google.com` from the command line, assuming Chrome is already open. I'll take a look into your suggestions from the other issue, but may not get much time to dig in.

**Comment by copiousfreetime** [comment]
closing as a stale issue.
