### ISSUE TITLE
running on cloud9

### ISSUE THREAD

**Issue by tansaku** [copiousfreetime/launchy#111]
has anyone managed to get launchy to work on cloud9? 

I get:

```
  Scenario: Creating category            # features/create_category.feature:6
    Given the blog is set up             # features/step_definitions/web_steps.rb:34
    And I am logged into the admin panel # features/step_definitions/web_steps.rb:46
    When I am on the admin page          # features/step_definitions/web_steps.rb:73
xprop:  unable to open display ''
xprop:  unable to open display ''
    And show me the page                 # features/step_definitions/web_steps.rb:281
      Unable to find a browser command. If this is unexpected, Please rerun with environment variable LAUNCHY_DEBUG=true or the '-d' commandline option and file a bug at https://github.com/copiousfreetime/launchy/issues/new (Launchy::CommandNotFoundError)
      ./features/step_definitions/web_steps.rb:282:in `/^show me the page$/'
      features/create_category.feature:11:in `And show me the page'
```

**Comment by copiousfreetime** [comment]
Hi @tansaku  Launchy attempts to find an installed browser locally on the machine that Launchy is running on. If you are using launchy in a remote machine/heroku/vps/docker scenario it will attempt to launch a web browser process on that container/remote machine where the ruby process is running.

In your cloud9 case, it is attempting to find a browser on the remote cloud9 box and open the browser on that machine. It looks like cloud9 is effectively a docker container, so you'll have the same problem as #108. There is no way for Launchy, which is running on the server side, in the docker container, to tell your desktop to open up a browser to a new URL.

**Comment by tansaku** [comment]
thanks @copiousfreetime - much appreciated :-)

**Comment by andela-ajamiu** [comment]
Using `[letter_opener_web](https://github.com/fgrehm/letter_opener_web)` gem fixed that for me
