### ISSUE TITLE
Launchy can't detect my browsers

### ISSUE THREAD

**Issue by gentoid** [copiousfreetime/launchy#112]
Being on Gentoo Linux I have following browsers installed:
- `firefox-bin`
- `google-chrome-stable`

We use `letter_opener` to check emails in development mode, but it can't open any. With `LAUNCHY_DEBUG=true` I can see it tries to detect browser from the predefined list, but the list doesn't contain that ones I have on my computer. Is there a way to add my custom browsers to check? Something like config in `~/`, or in the project root.

**Comment by copiousfreetime** [comment]
@gentoid Launchy will use the `$BROWSER` environment variable if it is set. It effectively follows the idea from http://www.catb.org/esr/BROWSER/index.html including the `%s` substitution. 

* https://help.ubuntu.com/community/EnvironmentVariables
* https://wiki.archlinux.org/index.php/environment_variables

If you also have `xdg-open` installed and it is configured to open your preferred browser then that is also an option.

**Comment by copiousfreetime** [comment]
@gentoid I've updated the README with example `BROWSER` usage, let me know if that helps for you.

**Comment by gentoid** [comment]
@copiousfreetime thanks for so fast response :+1: 

I've just tried what you've added 
```
BROWSER="/usr/bin/firefox-bin -new-tab '%s':/usr/bin/google-chrome-stable" irb
2.3.1 :002 > require 'launchy'
 => true 
2.3.1 :003 > Launchy::Browser.run("http://www.ruby-lang.org/")
WARNING: You made a call to a deprecated Launchy API. This call should be changed to 'Launchy.open( uri )'
 => #<Process::Waiter:0x00000001320ef0 sleep
```
In this case it works, but when I intentionally mistyped path for the first browser in the $BROWSER, it throws an exception:
```
$ BROWSER="/usr/bin/firefox-binn -new-tab '%s':/usr/bin/google-chrome-stable" irb
2.3.1 :001 > require 'launchy'
 => true 
2.3.1 :002 > Launchy::Browser.run("http://www.ruby-lang.org/")
WARNING: You made a call to a deprecated Launchy API. This call should be changed to 'Launchy.open( uri )'
 => #<Process::Waiter:0x00000000b68820 run> 
2.3.1 :003 > ... skipped... No such file or directory - /usr/bin/firefox-binn (Errno::ENOENT)
```
And doesn't try next one in the list.

But anyway, it solves my case, and the case with mistyped path(s) is sort of another issue :-)

**Comment by copiousfreetime** [comment]
@gentoid Well, it certainly helps if my example uses the proper api doesn't it :-). use `Launchy.open(...)` instead. I just updated the README. I'll make a note of that bug and get working on it.
