### ISSUE TITLE
Opening a local file

### ISSUE THREAD

**Issue by dekhaus** [copiousfreetime/launchy#116]
Hi

Is it possible to open a local file with Launchy ?   I have a directory of 'mail' files (aka files generated as a result of setting config.action_mailer.delivery_method to :file in Rails app) and I would like to open those files in the Mail application (on a mac) in response to a user clicking on a link in a browser to said email.

Thanks
Dave

**Comment by copiousfreetime** [comment]
@dekhaus if a user is clicking on a link in your web browser, then the browser is what will control what happens with that url. If you are looking at mail sent in a rails app for development/testing purposes, I would probably suggest you use something like https://github.com/ryanb/letter_opener (which uses launchy under the covers). If that doesn't work for you there are a couple of other alternatves mentioned in the Letter Opener documentation that might work for you also.
