### ISSUE TITLE
Add Launchy Functionality for Windows Subsystem for Linux Edge Case

### ISSUE THREAD

**Issue by APayden** [copiousfreetime/launchy#117]
Launchy does not currently work for the edge case regarding the use of the Ubuntu Bash Subsystem that Windows 10 implements.  It would be nice for the implementation to make use of the functionality that Windows offers and help launch the browser if I'm using the subsystem.

**Comment by copiousfreetime** [comment]
@ACPPPF happy to have a pull request for this if you like. Unfortunately I don't have any Windows 10 systems so I'm not in a position to work on it myself.

**Comment by swiftster** [comment]
FWIW, I was able to work around this by setting the $BROWSER variable.
`export BROWSER='/mnt/c/Program\ Files\ \(x86\)/Google/Chrome/Application/chrome.exe'`

**Comment by Faisal-nfl** [comment]
it only opens browser but file fails due to path

**Comment by dersnek** [comment]
> FWIW, I was able to work around this by setting the $BROWSER variable.
> `export BROWSER='/mnt/c/Program\ Files\ \(x86\)/Google/Chrome/Application/chrome.exe'`

No matter what I set my $BROWSER variable to, it opens the application but doesn't open anything inside it, just a new empty window.

**Comment by dersnek** [comment]
It tries to use the next path: `file://home/*`, while with WSL the path is `file://wsl%24/#{wsl-name}/home/`

**Comment by copiousfreetime** [comment]
Closing this as no one has submitted a PR to help solve this and I do not own any Windows 10 machines in order to solve this myself. If anyone is able to resolve this issue, please submit a PR. Thanks.

**Comment by dersnek** [comment]
In case anyone faces the same issue and stumbles upon this thread, I wrote a simple gem which modified pages/screenshots paths so that it opens in Windows browsers from WSL (you still need to add `$BROWSER` variable) - https://github.com/dersnek/capybara-wsl

**Comment by dersnek** [comment]
@copiousfreetime I can add this path modification to Launchy, but WSL check would be a bit sketchy, something like `grep -qEi "(Microsoft|WSL)" /proc/version &> /dev/null`. It works now, in theory should work forever. Or maybe I can just add a @wsl variable that would be set manually?

**Comment by romka69** [comment]
@dersnek 
It really works. Thanks for fix launchy on WSL.

**Comment by Taeir** [comment]
The fix given above did not work for me since I use launchy for previewing emails, and paths were getting messed up due to the `file://` part. What I did was the following:

Add an "executable" named `wslopen` (e.g. in ~/.local/bin):
```bash
#!/bin/bash
/mnt/c/Windows/explorer.exe "file://$(wslpath -m ${1/"file://"/})"
```
Ensure that it is executable with `chmod +x wslopen`

Add to your `.bashrc`:
```bash
export BROWSER='wslopen'
```

This will open everything with whatever program is associated with it under windows (HTML in browser, txt in notepad, etc.). You can also replace the path to explorer.exe with the path to your browser if you prefer.

If you want to set this up quickly, run the following set of commands:
```bash
echo '#!/bin/bash' >> ~/.local/bin/wslopen
echo '/mnt/c/Windows/explorer.exe "file://$(wslpath -m ${1/"file://"/})"' >> ~/.local/bin/wslopen
chmod +x ~/.local/bin/wslopen
echo 'export BROWSER="wslopen"' >> ~/.bashrc
```

**Comment by odinsride** [comment]
@Taeir Thanks for this workaround, it worked perfectly for me.  I'll also note that I had to add `~/.local/bin` to my `$PATH` as it did not exist already.

**Comment by brunoprietog** [comment]
I had to use ´/mnt/c/Windows/explorer.exe "file://$(wslpath -w ${1/"file://"/})"´ instead, switching from ´-m´ to ´-w´ argument.
