### ISSUE TITLE
Open new browser behind the current active browser and window resize

### ISSUE THREAD

**Issue by Rubioli** [copiousfreetime/launchy#118]
Great gem 👍 

Is it possible to open the new browser in the background. Lets say I already have chrome up, when I run the program, I don't want new browser to open on top of the current/active browser *(and hide the current/active browser)*, but open it behind the current/active *(so its hidden behind the current/active browser)*.

Is it possible to resize the newly opened browser so its not maximized?

Any help is appreciated!

**Comment by copiousfreetime** [comment]
@Rubioli That is both Operating System and browser dependent. If there is a commandline switch to chrome that that means the "open a new window behind the current window" then you could [use the `BROWSER` environment variable to do so](https://github.com/copiousfreetime/launchy#using-the-browser-environment-variable).
