### ISSUE TITLE
Can I run in production?

### ISSUE THREAD

**Issue by Rubioli** [copiousfreetime/launchy#119]
I'm running my application on Nginx & Passenger server with `rbenv_ruby 2.3.1`, `Rails 4.2.4` and `launchy 2.4.3`.

In my development ENV everything works fine, but when I try to run in production server, I get this error:
![skjermbilde 2017-09-28 kl 15 32 55](https://user-images.githubusercontent.com/16593596/30969332-59cc4ef0-a462-11e7-859d-b7bba157ebf8.png)

This is how I've done it:

*My `Browser` model:*
```
class Browser < ActiveRecord::Base

  def self.open
    Launchy.open("http://stackoverflow.com")
  end

```
*My `PageController`:*
```
class PagesController < ApplicationController

  def index
    Browser.open
  end
```

Any help is appreciated

**Comment by copiousfreetime** [comment]
@Rubioli This means that launchy was unable to find the command line executable of any browser it knows about on the machine that it is currently on. On a server, this is probably normal, typically a production server probably does not have a GUI interface, in all likelihood does not have any display connected, and therefore no chrome, no firefox etc. So unless you are using a remote desktop application of some type with your server, this is what I would expect.

Launchy opens up a browser on the machine that launchy is running on. In your dev environment, that means it opens a browser and displays it on your development machine. Which has a GUI, and has browser applications installed on the machine.

You could install chrome or firefox on your server and then launchy would launch them. But, where would they browser actually be displayed? 

Hopefully this makes sense. If you want to explain more about what your application is doing, and what you are expecting  to happen, then I may be able to help.

**Comment by Rubioli** [comment]
Thanks a lot, @copiousfreetime.

Yeah, that makes sense. 

To explain a little about the platform and how we want to use Launchy so it may give a better picture.
We are experimenting with a platform for intern use. The platform will be opened by a pop-up window from chrome or firefox browser (on our computer/machine) & this pop-up browser window will need to open a new browser (same browser & machine they use) and go to a link.

As mentioned this works fine in development and after you described how & why, it makes sense why it didn't work in production server.

We are using `Ubuntu 14.04.4 LTS (GNU/Linux 3.13.0-88-generic x86_64)`, along with Ngnix and passenger for our rails 4.2.4 app.

I would appreciate it if you could help me out setting this up so production server opens the new browser from Launchy.

Thanks a bunch

**Comment by copiousfreetime** [comment]
Considering you probably don't have a display connected to the server; and the rails session probably does not have an XWindows/Gnome/KDE session in order for firefox/chrome to attach to and  display the browser on a screen; this makes sense.

Either set `LAUNCHY_DEBUG=true` as an environment variable on your server so it gets passed to the rails app, or in a rails initializer do something like `ENV['LAUNCHY_DEBUG'] = "true"`.  Or call launchy like `Launchy.open(url, { :debug => true })`. If you do any of them then you will get a bunch of `LAUNCHY_DEBUG: ... ` line on `$stderr` which you can use to debug further.

**Comment by Rubioli** [comment]
Thanks for your reply, @copiousfreetime 

I changed my `Browser` to this:
```
class Browser < ActiveRecord::Base
  require 'launchy'

  def self.open
    Launchy.open("http://stackoverflow.com", { :debug => true })
  end
```
*This is the log in got from **DEVELOPMENT ENV**:*
```
Started GET "/" for ::1 at 2017-09-28 20:47:26 +0200
Processing by PagesController#index as HTML
LAUNCHY_DEBUG: URI parsing pass 1 : http://stackoverflow.com -> {:scheme=>"http", :user=>nil, :password=>nil, :host=>"stackoverflow.com", :port=>nil, :path=>"", :query=>nil, :fragment=>nil}
LAUNCHY_DEBUG: Checking if class Launchy::Application::Browser is the one for handles?(http://stackoverflow.com)}
LAUNCHY_DEBUG: Checking if class Launchy::Detect::HostOsFamily::Windows is the one for matches?(darwin14.1.0)}
LAUNCHY_DEBUG: Checking if class Launchy::Detect::HostOsFamily::Darwin is the one for matches?(darwin14.1.0)}
LAUNCHY_DEBUG: Checking if class Launchy::Detect::RubyEngine::Mri is the one for is_current_engine?(ruby)}
LAUNCHY_DEBUG: Checking if class Launchy::Detect::HostOsFamily::Windows is the one for matches?(darwin14.1.0)}
LAUNCHY_DEBUG: Checking if class Launchy::Detect::HostOsFamily::Darwin is the one for matches?(darwin14.1.0)}
LAUNCHY_DEBUG: Checking if class Launchy::Detect::RubyEngine::Mri is the one for is_current_engine?(ruby)}
LAUNCHY_DEBUG: Launchy::Application : found executable /usr/bin/open
LAUNCHY_DEBUG: Launchy::Application::Browser : possibility from app_list : /usr/bin/open
LAUNCHY_DEBUG: Launchy::Application : found executable /usr/bin/open
LAUNCHY_DEBUG: Launchy::Application::Browser : Using browser value '/usr/bin/open'
LAUNCHY_DEBUG: wet_run: before exec in child process
LAUNCHY_DEBUG: commandline_normalized => /usr/bin/open http://stackoverflow.com
  Rendered pages/index.html.erb within layouts/application (25.0ms)
Completed 200 OK in 701ms (Views: 562.9ms | ActiveRecord: 0.0ms)
```

**But** when I check my `production.log`, I can't see any `LAUNCHY_DEBUG`. *This is what I get:*
```
I, [2017-09-28T16:26:41.850646 #11376]  INFO -- : Completed 200 OK in 49ms (Views: 9.0ms | ActiveRecord: 0.0ms)
D, [2017-09-28T16:29:29.804753 #12007] DEBUG -- :   ESC[1mESC[36mActiveRecord::SchemaMigration Load (0.6ms)ESC[0m  ESC[1mSELECT "schema_migrations".* FROM "schema_migrations"ESC[0m
I, [2017-09-28T16:30:56.633745 #12188]  INFO -- : Started GET "/" for 92.221.31.84 at 2017-09-28 16:30:56 -0400
I, [2017-09-28T16:30:56.698236 #12188]  INFO -- : Processing by PagesController#index as HTML
I, [2017-09-28T16:30:56.759688 #12188]  INFO -- :   Rendered pages/index.html.erb within layouts/application (1.7ms)
I, [2017-09-28T16:30:56.765603 #12188]  INFO -- : Completed 200 OK in 67ms (Views: 18.1ms | ActiveRecord: 0.0ms)
I, [2017-09-28T16:33:58.910709 #12188]  INFO -- : Started GET "/" for 92.221.31.84 at 2017-09-28 16:33:58 -0400
I, [2017-09-28T16:33:58.945296 #12188]  INFO -- : Processing by PagesController#index as HTML
I, [2017-09-28T16:33:59.002362 #12188]  INFO -- :   Rendered pages/index.html.erb within layouts/application (0.3ms)
I, [2017-09-28T16:33:59.006044 #12188]  INFO -- : Completed 200 OK in 60ms (Views: 9.4ms | ActiveRecord: 0.0ms)
```

In `environments/production.rb` I do:
`config.log_level = :debug`

I appreciate your help and hope you can show me what to do and how to get the log up.

**Comment by copiousfreetime** [comment]
@Rubioli the launchy debug logs got to `$stderr` so wherever that is sent in your rails is where it has gone. I would also check the nginx/passenger logs, good probability that they might be in there.

**Comment by Rubioli** [comment]
Thanks! Nothing in nginx/passenger logs, but I'm looking further to find it.  Just to clarify about what I try to achieve and maybe you can suggest a better & faster setup.

As mentioned I'm experimenting with a platform. So basically I want to send some to a public website, *(we can call it www.mydomain.com)*, the site is not running locally on my machine and it's on a dedicated server *(Amazon AWS or digital ocean)*. When he comes to this page, I want it to open a new browser and go to **http://www.stackoverflow.com** *(as Launchy already do)*.

The web application can be on Rails or Sinatra. For achieving this what setup do you suggest so that it works and can be achieved better and faster?

I appreciate your help and thanks for taking your time :) 👍

**Comment by copiousfreetime** [comment]
Just making sure I understand what you want to have happen:

1. A user out in the internet clicks on a link you provide (probably in an email or another webpage) and that link sends them to https://mydomain.example.com (your domain your server)
2. Your server takes some action that causes the client (some laptop elsewhere in the world) that clicked on that link to open a new browser window on the client's machine.

Launchy is the wrong tool for this job. Launchy executes a command line program (firefox, chrome, etc) on the machine that launchy itself is running on.  In your production instance this is your server. Your server is not the clients' machine, and can in no way execute a command line program on the client's machine.

In your development environment it happens that the client machine and the server machine are the same machine. Your machine.

I have a feeling you are missing some fundamental concepts, and you should look into <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a" target="_blank"><tt>&lt;a href=".." target="_blank"&gt;</tt></a>

**Comment by Rubioli** [comment]
Thanks for your description, @copiousfreetime and it does make sense. 

The reason I don't use `<a href=".." target="_blank">` is because the provided link https://mydomain.example.com *(my domain in my server)* will need to be open as a pop-up and I need to open a new link with a *complete* browser functionality *with/from* this pop-under.

The reason is because of some functionality that will not work/stopped when the page is opened in pop-up window and the browser needs to be a *complete browser*.

As of now, I understand it can't be done with launchy as you described, but do you think is there any other ways to achieve this? I appreciate if you could give me some points.

Appreciate you take your time!
