### ISSUE TITLE
Launchy Applet not starting: undefined method `to_hash' for nil:NilClass

### ISSUE THREAD

**Issue by mgbckr** [copiousfreetime/launchy#120]
Hi,

Just yesterday, I have updated my Ubuntu. Since then, when I want to start launchy (simply typing `launchy` on the terminal, which used to start my desktop applet reacting to a shortcut calling launchy), I get the following debug output:

```
ERROR: Failure in opening uri nil with options {:debug=>true}: undefined method `to_hash' for nil:NilClass
Did you mean?  to_h
LAUNCHY_DEBUG: ERROR: Failure in opening uri nil with options {:debug=>true}: undefined method `to_hash' for nil:NilClass
Did you mean?  to_h
LAUNCHY_DEBUG: /var/lib/gems/2.3.0/gems/launchy-2.4.3/lib/launchy.rb:34:in `rescue in open'
LAUNCHY_DEBUG: /var/lib/gems/2.3.0/gems/launchy-2.4.3/lib/launchy.rb:40:in `open'
LAUNCHY_DEBUG: /var/lib/gems/2.3.0/gems/launchy-2.4.3/lib/launchy/cli.rb:68:in `good_run'
LAUNCHY_DEBUG: /var/lib/gems/2.3.0/gems/launchy-2.4.3/lib/launchy/cli.rb:86:in `run'
LAUNCHY_DEBUG: /var/lib/gems/2.3.0/gems/launchy-2.4.3/bin/launchy:4:in `<top (required)>'
LAUNCHY_DEBUG: /usr/local/bin/launchy:23:in `load'
LAUNCHY_DEBUG: /usr/local/bin/launchy:23:in `<main>'
Try `launchy --help' for more information.
```
When I run something like  `launchy "https://google.com"` launchy starts a browser window correctly.

**Update**: After looking into this more closely, I am not sure anymore if this launchy project has anything to do with the [launchy application launcher](https://www.launchy.net/).

**Comment by mgbckr** [comment]
Well `launchy != launchy` ;) after checking you source code and the one from https://www.launchy.net/ this became apparent :)  Thus, I found the issue ... here is the story:

* I installed [travis-ci command line client](https://github.com/travis-ci/travis.rb) which installs your ruby gem called `launchy` and puts it on the PATH, so that it can be executed directly from the terminal.
* This overwrites the original `launchy` executable. Thus, when I type `launchy` your ruby gem "launchy" is executed instead of the application launcher "launchy".
* The update process I mentioned earlier is significant, because I only noticed this, after rebooting my machine.
* I solved the issue by changing my startup configuration to directly call `/usr/bin/launchy` instead of `launchy`.

Sorry for the confusion!

**Comment by copiousfreetime** [comment]
@mgbckr No worries, this wouldn't be the first time the two projects have been confused. Although this is the first time that I'm aware of that one installed on top of the other. I'll have to keep an eye out for the travis ci tools, maybe they should have a bug report on their side that says it should deal with existing executables.

**Comment by mgbckr** [comment]
I guess that makes sense. I opened a corresponding bug report: https://github.com/travis-ci/travis.rb/issues/550
