### ISSUE TITLE
Launchy 2.4.3 doesn't seem to use application setting at all.

### ISSUE THREAD

**Issue by matthewtuck** [copiousfreetime/launchy#121]
It looks like launchy does not use the "application" setting at all, contrary to documentation. It seems to always be ignored, and in a cursory search I can't find anywhere in the source where the ````Launchy.application```` method is used.

I was trying this in the context of a data URI which I assume is an unsupported feature. But the documentation suggests I should be able to force this to the browser.

    » launchy data:image/png;base64,omitted_data==
    ERROR: No application found to handle 'data:image/png'
    Try `launchy --help' for more information.

    » launchy data:image/png;base64,omitted_data== --application Browser
    ERROR: No application found to handle 'data:image/png'
    Try `launchy --help' for more information.

**Comment by copiousfreetime** [comment]
That does appear to be the case.  I think that was a goal early on when I pondered launchy doing more than only Browser. Since there is only one application, I think I'll change it so that it is `--force-browser` or something along those lines.
