### ISSUE TITLE
No report is generated

### ISSUE THREAD

**Issue by surajmoda** [copiousfreetime/launchy#122]
New critique at file:///home/ubuntu/workspace/tmp/rubycritic/overview.html
xprop:  unable to open display ''
xprop:  unable to open display ''
Attempted to open file:///home/ubuntu/workspace/tmp/rubycritic/overview.html and failed because Unable to find a browser command. If this is unexpected, Please rerun with environment variable LAUNCHY_DEBUG=true or the '-d' commandline option and file a bug at https://github.com/copiousfreetime/launchy/issues/new

I treid with adding environment variable but it did not work.

**Comment by copiousfreetime** [comment]
Hi @surajmoda, are you running launchy on a headless machine? Can you tell me more about what you are attempting to do and what you are expecting to happen?

**Comment by copiousfreetime** [comment]
No response from upstream, closing.
