### ISSUE TITLE
Settings get cleared after some time

### ISSUE THREAD

**Issue by dmersiowsky** [copiousfreetime/launchy#123]
Not sure if duplicate, definitely not fixed until v2.5: Launchy Settings and Database keep getting cleared every now and then. It is barely reproducable but happens over and over. 

Settings get cleared to defaults. Happens with portable and installer version, can confirm it happens on Win10 and Win7.

**Comment by copiousfreetime** [comment]
For future reference, I believe this was a confusion between my project and http://www.launchy.net/
