### ISSUE TITLE
Anyway to set the browser tab like in <a href="" target="">?

### ISSUE THREAD

**Issue by bretweinraub** [copiousfreetime/launchy#129]
I can do 

`Launch.open(_url_)`

which is beautiful.   Would really love to be able to do

`Launch.open(_url_, target: 'tag')`

like in an anchor tag.

**Comment by copiousfreetime** [comment]
I don't really know off the top of my head - it would require command line options on the various browsers - I'll do a quick look and see if any of them have it.

**Comment by bretweinraub** [comment]
Command line eh?   I did a deep dive on the Chrome command line docs but didn't come up with anything......

**Comment by copiousfreetime** [comment]
yup - command line - that's how launchy is able to work - it figures out a browser / os combination, then generates the appropriate command line and executes it.

**Comment by copiousfreetime** [comment]
By default it should open in a new tab on most browsers - at least it does for me. Although I don't have every browser and os combination to test.

**Comment by bretweinraub** [comment]
Yeah, it does.   But there's no way in Chrome to set the tab target on the command line it seems.   Thanks for looking into it.   I never made it to boulder.rb .... but Denver, yes.

**Comment by copiousfreetime** [comment]
Alright - going to closes this issue then. Doesn't look like its feasible.
