### ISSUE TITLE
Launchy seems to error since 28th Feb since 2.5.0 was released

### ISSUE THREAD

**Issue by sajithakak** [copiousfreetime/launchy#133]
https://github.com/cloudfoundry/cf-uaac/issues/82

The following used to work till last week

Now [Erroring since 28th Feb 2020]:
Building native extensions. This could take a while...
ERROR: Error installing cf-uaac:
launchy requires Ruby version >= 2.4.0.
Successfully installed eventmachine-1.2.7
Successfully installed public_suffix-4.0.3
Successfully installed addressable-2.7.0
ERROR: Job failed: exit code 1

======

Before:[Working]
Building native extensions. This could take a while...
Successfully installed eventmachine-1.2.7
Successfully installed public_suffix-4.0.3
Successfully installed addressable-2.7.0
Successfully installed launchy-2.4.3

is this is anyway related to 2.5.0 version pls ?

**Comment by copiousfreetime** [comment]
@sajithakak The launchy release really was just updating dependencies and a minimum ruby version. There is the possibility that this have introduced a dependency issue somewhere. If you could attach the output of `bundle env` and `gem env` and `ruby --version` along with a more complete commandline example of  what you are executing on the commandline I'll see what I can come up with.

**Comment by sajithakak** [comment]
Thank you soo much. We are trying to use - https://github.com/cloudfoundry/cf-uaac.
We updated our ruby version to 2.5.1 and all good now. Thanks a lot.

**Comment by copiousfreetime** [comment]
@sajithakak sounds good - that was one of the updates - I set launchy to have a minimum ruby vesion to be the lowest level of supported rubies. Which is currently 2.4.9. Good to know that updating your ruby fixed your issue.
