### ISSUE TITLE
Launchy::CommandNotFoundError

### ISSUE THREAD

**Issue by lam-way** [copiousfreetime/launchy#137]
Launchy::CommandNotFoundError: Unable to find a browser command. If this is unexpected, Please rerun with environment variable LAUNCHY_DEBUG=true or the '-d' commandline option and file a bug at https://github.com/copiousfreetime/launchy/issues/new

**Comment by copiousfreetime** [comment]
please follow the instructions and rerun with either  `-d` on the command line or setting `LAUNCHY_DEBUG=true` and update this ticket as appropropriate.
