### ISSUE TITLE
Launchy 2.5 introduces breaking changes by requiring ruby 2.4

### ISSUE THREAD

**Issue by llucax** [copiousfreetime/launchy#139]
Hi, I'm using `travis` which depends on launchy. Last time I got it, it used launchy 2.4.x and all was fine. Now when I try to get it but it fails because its resolving the dependency to launchy 2.5.0 but I'm using Ubuntu Xenial which only comes with ruby2.3 and it seems like launchy now requires 2.4. I think this shouldn't happen with a minor release. Is there any way to make the 2.5 series compatible with ruby2.3? If not I guess version 2.5 should be marked somehow broken and change it to be 3.0.0 to avoid further breakage.

This is happening in an open source project CI BTW, so you can [have a look at the log](https://travis-ci.org/github/sociomantic-tsunami/cachalot/jobs/739534388#L2875) in case it helps in any way. And [here you can see how it worked before](https://travis-ci.org/github/sociomantic-tsunami/cachalot/jobs/599719587#L1846).

**Comment by copiousfreetime** [comment]
I've downreved a development dependency which was the reason to bump to 2.4, that and ruby 2.3 was EOL March 31, 2019. Next release will allow ruby 2.3 again.
