### ISSUE TITLE
Launchy::CommandNotFoundError

### ISSUE THREAD

**Issue by shubham-singh-chouhan** [copiousfreetime/launchy#141]
Launchy::CommandNotFoundError: Unable to find a browser command. If this is unexpected, Please rerun with environment variable LAUNCHY_DEBUG=true or the '-d' commandline option and file a bug at https://github.com/copiousfreetime/launchy/issues/new
from /usr/local/bundle/gems/launchy-2.5.0/lib/launchy/applications/browser.rb:63:in `browser_cmdline'

**Comment by copiousfreetime** [comment]
Please follow the instructions given on that output above. Reopen this ticket if there is an issue that isn't resolved with the debug text
