### ISSUE TITLE
Arc Integration

### ISSUE THREAD

**Issue by MtnBiker** [copiousfreetime/launchy#151]
Launch doesn't seem to work with Arc, a new browser in early roll out.

Longtime Launchy user.

Thank you

**Comment by copiousfreetime** [comment]
Hi @MtnBiker - if you have access to Arc and want to debug this - set `LAUNCHY_DEBUG=true` to get a trace - and use the `BROWSER` environment variable (see the README) to attempt to get arc to be launched and then drop that trace in here and I'll see what we can do.

**Comment by MtnBiker** [comment]
Where do I put` LAUNCHY_DEBUG=true`?

Tried in .zshrc and in my script and don’t see anything. I looked quickly in the Console.app in macOS and didn’t see anything.

Use case: I have a ruby script with a bunch of urls, some run every day, others every 1, 3, x days and some random ones. macOS, recent ruby

I tried this setting the default browser to Arc in the browser. Works fine with Safari (what I normally use for casual browsing) and Chrome. In both it opens each URL in a new tab.

In Arc running the script opens a “Little Arc Window” which is looks like a modal or popup window. From that window there is an option o open a “regular” window. So each new url from the script writes over the previous one and you only end up with the last item in the script.

I’m no programmer, so take any description with hesitation.

￼

Main window in background and last item in script in foreground.

I’m guessing you haven’t tried Arc (maybe you’re not even on macOS), but it’s a new take on browsers. I’m just trying it out. Free for now, but assume will be a monthly charge.

Greg

**Comment by copiousfreetime** [comment]
I'm on a mac, and on the waiting list for arc now - so I'll probably be able to work with it whenever I get an invite.

If you posted an image into you response, it doesn't look like it came through to the ticket.

On a mac, launchy by default, does the same as if you executed `open <url>` on the command line.  So if that works on the command line and opens up that url in arc the way you want, then you should be good. 

I think that if you can set arc as the default browser for the system - that should work. Personally I have firefox set as the default browser for the system and when I do `open https://github.com/` in a shell, it opens up github in a new tab in firefox. I also had to change my firefox preferences in order to have a new url opened in a tab instead of a new window. So there may be preferences that needs to be updated in arc.

To turn on the debugging, if you are using a ruby script, then just change the `Launchy.open(url)` to `Launchy.open(url, debug: true)`. 

You could also do this from `irb`:

```
% irb
>> require 'launchy'
>> Launchy.open("https://github.com", debug: true)
LAUNCHY_DEBUG: URI parsing pass 1 : https://github.com -> {:scheme=>"https", :user=>nil, :password=>nil, :host=>"github.com", :port=>nil, :path=>"", :query=>nil, :fragment=>nil}
LAUNCHY_DEBUG: Checking if class Launchy::Application::Browser is the one for handles?(https://github.com)}
LAUNCHY_DEBUG: Checking if class Launchy::Detect::HostOsFamily::Windows is the one for matches?(darwin21)}
LAUNCHY_DEBUG: Checking if class Launchy::Detect::HostOsFamily::Darwin is the one for matches?(darwin21)}
LAUNCHY_DEBUG: Checking if class Launchy::Detect::RubyEngine::Mri is the one for is_current_engine?(ruby)}
LAUNCHY_DEBUG: Checking if class Launchy::Detect::HostOsFamily::Windows is the one for matches?(darwin21)}
LAUNCHY_DEBUG: Checking if class Launchy::Detect::HostOsFamily::Darwin is the one for matches?(darwin21)}
LAUNCHY_DEBUG: Checking if class Launchy::Detect::RubyEngine::Mri is the one for is_current_engine?(ruby)}
LAUNCHY_DEBUG: Launchy::Application : found executable /usr/bin/open
LAUNCHY_DEBUG: Launchy::Application::Browser : possibility from app_list : /usr/bin/open
LAUNCHY_DEBUG: Launchy::Application : found executable /usr/bin/open
LAUNCHY_DEBUG: Launchy::Application::Browser : Using browser value '/usr/bin/open'
LAUNCHY_DEBUG: wet_run: before exec in child process
LAUNCHY_DEBUG: commandline_normalized => /usr/bin/open https://github.com
```

**Comment by MtnBiker** [comment]
I only waited a couple of days to get invited.

Starting benchmark at 2023-05-04 17:30:42 -0700

LAUNCHY_DEBUG: URI parsing pass 1 : http://www.lamag.com/ -> {:scheme=>"http", :user=>nil, :password=>nil, :host=>"www.lamag.com", :port=>nil, :path=>"/", :query=>nil, :fragment=>nil}
LAUNCHY_DEBUG: Checking if class Launchy::Application::Browser is the one for handles?(http://www.lamag.com/)}
LAUNCHY_DEBUG: Checking if class Launchy::Detect::HostOsFamily::Windows is the one for matches?(darwin21)}
LAUNCHY_DEBUG: Checking if class Launchy::Detect::HostOsFamily::Darwin is the one for matches?(darwin21)}
LAUNCHY_DEBUG: Checking if class Launchy::Detect::RubyEngine::Mri is the one for is_current_engine?(ruby)}
LAUNCHY_DEBUG: Checking if class Launchy::Detect::HostOsFamily::Windows is the one for matches?(darwin21)}
LAUNCHY_DEBUG: Checking if class Launchy::Detect::HostOsFamily::Darwin is the one for matches?(darwin21)}
LAUNCHY_DEBUG: Checking if class Launchy::Detect::RubyEngine::Mri is the one for is_current_engine?(ruby)}
LAUNCHY_DEBUG: Launchy::Application : found executable /usr/bin/open
LAUNCHY_DEBUG: Launchy::Application::Browser : possibility from app_list : /usr/bin/open
LAUNCHY_DEBUG: Launchy::Application : found executable /usr/bin/open
LAUNCHY_DEBUG: Launchy::Application::Browser : Using browser value '/usr/bin/open'
LAUNCHY_DEBUG: wet_run: before exec in child process
LAUNCHY_DEBUG: URI parsing pass 1 : http://www.sno.phy.queensu.ca/~phil/exiftool/ -> {:scheme=>"http", :user=>nil, :password=>nil, :host=>"www.sno.phy.queensu.ca", :port=>nil, :path=>"/~phil/exiftool/", :query=>nil, :fragment=>nil}
LAUNCHY_DEBUG: Checking if class Launchy::Application::Browser is the one for handles?(http://www.sno.phy.queensu.ca/~phil/exiftool/)}
LAUNCHY_DEBUG: Checking if class Launchy::Detect::HostOsFamily::Windows is the one for matches?(darwin21)}
LAUNCHY_DEBUG: Checking if class Launchy::Detect::HostOsFamily::Darwin is the one for matches?(darwin21)}
LAUNCHY_DEBUG: Checking if class Launchy::Detect::RubyEngine::Mri is the one for is_current_engine?(ruby)}
LAUNCHY_DEBUG: Checking if class Launchy::Detect::HostOsFamily::Windows is the one for matches?(darwin21)}
LAUNCHY_DEBUG: Checking if class Launchy::Detect::HostOsFamily::Darwin is the one for matches?(darwin21)}
LAUNCHY_DEBUG: Checking if class Launchy::Detect::RubyEngine::Mri is the one for is_current_engine?(ruby)}
LAUNCHY_DEBUG: Launchy::Application : found executable /usr/bin/open
LAUNCHY_DEBUG: Launchy::Application::Browser : possibility from app_list : /usr/bin/open
LAUNCHY_DEBUG: Launchy::Application : found executable /usr/bin/open
LAUNCHY_DEBUG: Launchy::Application::Browser : Using browser value '/usr/bin/open'
LAUNCHY_DEBUG: commandline_normalized => /usr/bin/open http://www.lamag.com/
LAUNCHY_DEBUG: wet_run: before exec in child process
LAUNCHY_DEBUG: commandline_normalized => /usr/bin/open http://www.sno.phy.queensu.ca/~phil/exiftool/
LAUNCHY_DEBUG: URI parsing pass 1 : https://alexonautos.com/category/green-vehicles/ -> {:scheme=>"https", :user=>nil, :password=>nil, :host=>"alexonautos.com", :port=>nil, :path=>"/category/green-vehicles/", :query=>nil, :fragment=>nil}
LAUNCHY_DEBUG: Checking if class Launchy::Application::Browser is the one for handles?(https://alexonautos.com/category/green-vehicles/)}
LAUNCHY_DEBUG: Checking if class Launchy::Detect::HostOsFamily::Windows is the one for matches?(darwin21)}
LAUNCHY_DEBUG: Checking if class Launchy::Detect::HostOsFamily::Darwin is the one for matches?(darwin21)}
LAUNCHY_DEBUG: Checking if class Launchy::Detect::RubyEngine::Mri is the one for is_current_engine?(ruby)}
LAUNCHY_DEBUG: Checking if class Launchy::Detect::HostOsFamily::Windows is the one for matches?(darwin21)}
LAUNCHY_DEBUG: Checking if class Launchy::Detect::HostOsFamily::Darwin is the one for matches?(darwin21)}
LAUNCHY_DEBUG: Checking if class Launchy::Detect::RubyEngine::Mri is the one for is_current_engine?(ruby)}
LAUNCHY_DEBUG: Launchy::Application : found executable /usr/bin/open
LAUNCHY_DEBUG: Launchy::Application::Browser : possibility from app_list : /usr/bin/open
LAUNCHY_DEBUG: Launchy::Application : found executable /usr/bin/open
LAUNCHY_DEBUG: Launchy::Application::Browser : Using browser value '/usr/bin/open'
LAUNCHY_DEBUG: wet_run: before exec in child process
LAUNCHY_DEBUG: commandline_normalized => /usr/bin/open https://alexonautos.com/category/green-vehicles/
LAUNCHY_DEBUG: URI parsing pass 1 : https://mirrorlesscomparison.com -> {:scheme=>"https", :user=>nil, :password=>nil, :host=>"mirrorlesscomparison.com", :port=>nil, :path=>"", :query=>nil, :fragment=>nil}
LAUNCHY_DEBUG: Checking if class Launchy::Application::Browser is the one for handles?(https://mirrorlesscomparison.com)}
LAUNCHY_DEBUG: Checking if class Launchy::Detect::HostOsFamily::Windows is the one for matches?(darwin21)}
LAUNCHY_DEBUG: Checking if class Launchy::Detect::HostOsFamily::Darwin is the one for matches?(darwin21)}
LAUNCHY_DEBUG: Checking if class Launchy::Detect::RubyEngine::Mri is the one for is_current_engine?(ruby)}
LAUNCHY_DEBUG: Checking if class Launchy::Detect::HostOsFamily::Windows is the one for matches?(darwin21)}
LAUNCHY_DEBUG: Checking if class Launchy::Detect::HostOsFamily::Darwin is the one for matches?(darwin21)}
LAUNCHY_DEBUG: Checking if class Launchy::Detect::RubyEngine::Mri is the one for is_current_engine?(ruby)}
LAUNCHY_DEBUG: Launchy::Application : found executable /usr/bin/open
LAUNCHY_DEBUG: Launchy::Application::Browser : possibility from app_list : /usr/bin/open
LAUNCHY_DEBUG: Launchy::Application : found executable /usr/bin/open
LAUNCHY_DEBUG: Launchy::Application::Browser : Using browser value '/usr/bin/open'
LAUNCHY_DEBUG: wet_run: before exec in child process
LAUNCHY_DEBUG: URI parsing pass 1 : https://greenercars.org -> {:scheme=>"https", :user=>nil, :password=>nil, :host=>"greenercars.org", :port=>nil, :path=>"", :query=>nil, :fragment=>nil}
LAUNCHY_DEBUG: Checking if class Launchy::Application::Browser is the one for handles?(https://greenercars.org)}
LAUNCHY_DEBUG: Checking if class Launchy::Detect::HostOsFamily::Windows is the one for matches?(darwin21)}
LAUNCHY_DEBUG: Checking if class Launchy::Detect::HostOsFamily::Darwin is the one for matches?(darwin21)}
LAUNCHY_DEBUG: commandline_normalized => /usr/bin/open https://mirrorlesscomparison.com
LAUNCHY_DEBUG: Checking if class Launchy::Detect::RubyEngine::Mri is the one for is_current_engine?(ruby)}
LAUNCHY_DEBUG: Checking if class Launchy::Detect::HostOsFamily::Windows is the one for matches?(darwin21)}
LAUNCHY_DEBUG: Checking if class Launchy::Detect::HostOsFamily::Darwin is the one for matches?(darwin21)}
LAUNCHY_DEBUG: Checking if class Launchy::Detect::RubyEngine::Mri is the one for is_current_engine?(ruby)}
LAUNCHY_DEBUG: Launchy::Application : found executable /usr/bin/open
LAUNCHY_DEBUG: Launchy::Application::Browser : possibility from app_list : /usr/bin/open
LAUNCHY_DEBUG: Launchy::Application : found executable /usr/bin/open
LAUNCHY_DEBUG: Launchy::Application::Browser : Using browser value '/usr/bin/open'
LAUNCHY_DEBUG: URI parsing pass 1 : https://paweldabrowski.com -> {:scheme=>"https", :user=>nil, :password=>nil, :host=>"paweldabrowski.com", :port=>nil, :path=>"", :query=>nil, :fragment=>nil}
LAUNCHY_DEBUG: Checking if class Launchy::Application::Browser is the one for handles?(https://paweldabrowski.com)}
LAUNCHY_DEBUG: Checking if class Launchy::Detect::HostOsFamily::Windows is the one for matches?(darwin21)}
LAUNCHY_DEBUG: Checking if class Launchy::Detect::HostOsFamily::Darwin is the one for matches?(darwin21)}
LAUNCHY_DEBUG: Checking if class Launchy::Detect::RubyEngine::Mri is the one for is_current_engine?(ruby)}
LAUNCHY_DEBUG: Checking if class Launchy::Detect::HostOsFamily::Windows is the one for matches?(darwin21)}
LAUNCHY_DEBUG: Checking if class Launchy::Detect::HostOsFamily::Darwin is the one for matches?(darwin21)}
LAUNCHY_DEBUG: Checking if class Launchy::Detect::RubyEngine::Mri is the one for is_current_engine?(ruby)}
LAUNCHY_DEBUG: Launchy::Application : found executable /usr/bin/open
LAUNCHY_DEBUG: Launchy::Application::Browser : possibility from app_list : /usr/bin/open
LAUNCHY_DEBUG: Launchy::Application : found executable /usr/bin/open
LAUNCHY_DEBUG: Launchy::Application::Browser : Using browser value '/usr/bin/open'
LAUNCHY_DEBUG: wet_run: before exec in child process
LAUNCHY_DEBUG: commandline_normalized => /usr/bin/open https://greenercars.org
LAUNCHY_DEBUG: wet_run: before exec in child process
LAUNCHY_DEBUG: commandline_normalized => /usr/bin/open https://paweldabrowski.com

The script took 0.067426 to complete per with_benchmark

**Comment by copiousfreetime** [comment]
Yup, its using `open` as I suspected - probably easiest if we just wait until I get my arc invite and then I can debug from there.

**Comment by MtnBiker** [comment]
Thank you. Works like a charm.

Has the advantage that I can choose which browser whether it's the default or not.

**Comment by MtnBiker** [comment]
@copiousfreetime posted the fix. Thank you
