### ISSUE TITLE
[FEATURE] Open Steam URI

### ISSUE THREAD

**Issue by maetthew** [copiousfreetime/launchy#58]
I'm not sure if this if I'm supposed to put this here put I figured you can just close it otherwise. I know that Launchy currently only supports opening HTTP URI's but I would like to propose a feature to open [Steam](http://steampowered.com) links.

Example link:
`steam://connect/81.0.1.1:27015/`

This will open Steam and I think that Steam itself recognizes which game the server is running, starts the correct game and connects to the server

**Comment by copiousfreetime** [comment]
Closing, lack of interest
