### ISSUE TITLE
Use bundler infrastructure instead of ad-hoc files

### ISSUE THREAD

**Issue by gioele** [copiousfreetime/launchy#66]
Hello,

I pushed at <https://github.com/gioele/launchy/tree/bundler> a commit that replaces the current infrastructure with a simplified Bundler-based Rakefile + gemspec. Using the now-default Bundler scripts makes it easier to package launchy, at least on Linux. It should also makes your life easier as there is less boilerplate code to be maintained.

This is not a pull request because I think of that code as just an attempt that needs a bit of supervision from the maintainers rather than a complete submission.

**Comment by copiousfreetime** [comment]
@gioele I'm cleaning up old tickets, and was wondering if there is still any issues with debian packaging of launchy, or have you fully worked around my failure to work on this in the past 2 years?

**Comment by copiousfreetime** [comment]
Closing, I haven't heard anything packaging issues in a while. Feel free to reopen.
