### ISSUE TITLE
Signed releases, por favor

### ISSUE THREAD

**Issue by steakknife** [copiousfreetime/launchy#80]
I even [wrote a gem](https://github.com/steakknife/waxseal) to make this easier:

```
[sudo] gem cert --add <(curl -L https://gist.github.com/steakknife/5333881/raw/gem-public_cert.pem) # adds my cert (do once)
[sudo] gem install waxseal -P HighSecurity
```

**Comment by copiousfreetime** [comment]
closing this as I'm probably not going to get around to it and there isn't a commonly used solution yet -- https://guides.rubygems.org/security/
