### ISSUE TITLE
At least one console web browser should be an option when launching a browser

### ISSUE THREAD

**Issue by trejkaz** [copiousfreetime/launchy#93]
I'm on a shell and trying to use some script which depends on launchy. It's trying to launch a browser, but it just fails:

    /usr/local/rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/launchy-2.4.3/lib/launchy/applications/browser.rb:63:in `browser_cmdline': Unable to find a browser command. If this is unexpected, Please rerun with environment variable LAUNCHY_DEBUG=true or the '-d' commandline option and file a bug at https://github.com/copiousfreetime/launchy/issues/new (Launchy::CommandNotFoundError)

I reran with debug and looked at the list of browser it's trying, but all of them are GUI ones. There are certainly a few browsers which will work in the console (I appear to have both links2 and w3m, which are probably among the more common options.)

In any case, throwing an exception doesn't help because the script now won't continue, so I can't even feed it the information I could have acquired from an external browser. Maybe in the absence of a browser it should print out the URL it was told to visit so that the user can do it manually.

**Comment by copiousfreetime** [comment]
this probably overlaps with #95 a bit.

**Comment by kichuku** [comment]
Is this feature implemented now?

**Comment by copiousfreetime** [comment]
@kichuku not yet, but it appears I'm doing a release of launchy soon, so I'm going to put this in it.
