### ISSUE TITLE
Opening just a raw file

### ISSUE THREAD

**Issue by ianks** [copiousfreetime/launchy#94]
I am looking to incorporate Launchy into my gem https://github.com/ianks/octodown and I need functionality to open a simple HTML file (not URL, etc.).

The only logic I really need from Launchy is the detection of the correction command line arguments to open a URL. If there isn't an option to do a file as of now, I will happily implement it, and if you can point me in the right direction that would be gracious :smile: 

Cheers!

**Comment by copiousfreetime** [comment]
no worries, let me know if there is anything you need.
