### ISSUE TITLE
Launchy didn't index on Launch

### ISSUE THREAD

**Issue by cefn** [copiousfreetime/launchy#96]
Installed Launchy in Lubuntu Utopic 14.10.

On launch, it had no entries, and I was required to run 'Rescan' for any entries to be added. I propose the feature that rescan should be run on first launch automatically so that Launchy can do its job effectively. It took quite a bit of navigating through menus to find the fix, and I'm sure most users would simply assume it was broken.

**Comment by copiousfreetime** [comment]
@cefn I think you may have the wrong project, could you be looking for http://www.launchy.net/ ?
