### ISSUE TITLE
Launchy associated executable .sh with Chrome!

### ISSUE THREAD

**Issue by cefn** [copiousfreetime/launchy#97]
Looks like I'll have to call short my experiments using Launchy as a launcher on Lubuntu 

That's because a core feature - running an executable - seems to be unusually configured by default. I've proven this issue across the latest in my distro (2.5-3) as well as the latest beta for Ubuntu 32 bit (2.6 beta 1)

I have a Menu item conforming to the .desktop freedesktop standard... https://linuxcritic.wordpress.com/2010/04/07/anatomy-of-a-desktop-file/

Which looks like the following, but amazingly launchy passes the .sh file to google-chrome to try and open it, which then offers to save the .sh file to my desktop. Pretty crazy behaviour when it should clearly run the executable .sh and launch Webstorm.

$ cat /home/cefn/.local/share/applications/jetbrains-webstorm.desktop 
[Desktop Entry]
Version=1.0
Type=Application
Name=WebStorm
Icon=/home/cefn/Developer/WebStorm-139.773/bin/webide.png
Exec="/home/cefn/Developer/WebStorm-139.773/bin/webstorm.sh" %f
Comment=Develop with pleasure!
Categories=Development;IDE;
Terminal=false
StartupWMClass=jetbrains-webstorm

**Comment by copiousfreetime** [comment]
Launchy is not a general application launcher, it is a cross platform web browser launcher. It is to be used within ruby programs to launch a web browser no matter what platform the code is running on.
