### ISSUE TITLE
How do i keep prompt after opening an URL ?

### ISSUE THREAD

**Issue by harvey56** [copiousfreetime/launchy#99]

**Comment by copiousfreetime** [comment]
@harvey56 How are you using launchy? Can you give me an example?

**Comment by harvey56** [comment]
sorry i was not clear.
I use Launchy in a function. I instantiate the class, and from within IRB, I call a function that has the Launchy method in it (Launchy.open('URL')).

Here is what i then get in IRB : 

2.2.0 :003 > myobject.myfunction
=> #< Process::Waiter:0x000000039a2600 sleep> 
2.2.0 :004 > 
(process:16265): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed

**Comment by copiousfreetime** [comment]
@harvey56 This is what happens to me when I attempt what you describe

```
% cat t.rb
require 'launchy'
class Issue99
  def doit
    Launchy.open("http://www.google.com")
  end
end
%irb -Ilib
>> load 't.rb'
>> i = Issue99.new
>> i.doit 
>>
```
When `i.doit` is invoked, my browser connects to google. Can you talk more about your environment you are in and maybe put your sample code in this ticket?

**Comment by copiousfreetime** [comment]
@harvey56 Any further insight on this issue? I'm going to close it for now. Please reopen if there is new information.
